# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Al Porotesano
email: al.porotesano@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Al Porotesano
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: nobleexperiment
github_username:  nobleexperiment
flickr:
  enabled:         yes
  cache_dir:       ./_cache/flickr
  api_key:         839452b9f95cb79fb40900c90b7e2f12
  shared_secret:   05c6b3c5fe6a5c9f
  auth_token: 
# Build settings
markdown: kramdown

# Create Tags
tags: 
- Wilmington
- Fiduciary_Advisor
- jekyll
- code
- Pokemon
- Porotesano
- Tutorial
- hackathon
- homeless
